using UnityEngine;
using UnityEngine.AI;

namespace StealthHuntAI.Combat
{
    /// <summary>
    /// Marks a position as valid cover for StealthHuntAI units.
    ///
    /// Two modes:
    ///   Auto-generated: created by CoverScanner, no manual setup needed
    ///   Manual:         place on any GameObject for precise control
    ///
    /// Manual CoverPoints always take priority over auto-generated ones.
    /// </summary>
    [AddComponentMenu("StealthHuntAI/Cover Point")]
    public class CoverPoint : MonoBehaviour
    {
        // ---------- Inspector -------------------------------------------------

        public enum CoverType { Low, High, Corner }

        [Tooltip("Low = crouch only. High = standing cover. Corner = peek both sides.")]
        public CoverType type = CoverType.Low;

        [Tooltip("Direction to peek out for firing. Auto-calculated if zero.")]
        public Vector3 peekDirection = Vector3.zero;

        [Tooltip("If true this point was generated by CoverScanner and may be removed.")]
        public bool isAutoGenerated = false;

        [Tooltip("Extra score bias. Higher = preferred by AI.")]
        [Range(0f, 2f)] public float scoreBias = 1f;

        // ---------- Runtime ---------------------------------------------------

        /// <summary>Currently occupying unit. Null if free.</summary>
        public StealthHuntAI Occupant { get; private set; }
        public bool IsOccupied => Occupant != null;

        /// <summary>World-space peek direction -- auto-calculated if not set.</summary>
        public Vector3 PeekDir
        {
            get
            {
                if (peekDirection.magnitude > 0.1f)
                    return peekDirection.normalized;
                // Default: forward of transform
                return transform.forward;
            }
        }

        // ---------- Scoring --------------------------------------------------

        private float _lastUsedTime = -999f;
        private int _useCount;

        public float TimeSinceUsed => Time.time - _lastUsedTime;

        /// <summary>Score this cover point for a given unit and target position.</summary>
        public float Evaluate(StealthHuntAI unit, Vector3 targetPos)
        {
            if (IsOccupied && Occupant != unit) return 0f; // already taken

            Vector3 pos = transform.position;

            // Protection -- does cover block line of sight from target?
            float protection = EvaluateProtection(pos, targetPos);

            // Proximity -- not too far to run, not too close to target
            float dist = Vector3.Distance(pos, unit.transform.position);
            float targetDist = Vector3.Distance(pos, targetPos);
            float proximity = 1f - Mathf.Clamp01(dist / 20f);
            float notTooClose = Mathf.Clamp01((targetDist - 3f) / 10f);

            // Visibility -- can we see target from here?
            float visibility = EvaluateVisibility(pos, targetPos);

            // Heat penalty -- avoid positions other units are using
            float heat = HuntDirector.GetHeat(pos);

            // Novelty -- avoid reusing same cover
            float novelty = Mathf.Clamp01(TimeSinceUsed / 15f);

            // Height bonus for high cover
            float heightBonus = type == CoverType.High ? 0.2f : 0f;

            return (protection * 0.30f
                  + proximity * 0.20f
                  + notTooClose * 0.10f
                  + visibility * 0.20f
                  + novelty * 0.10f
                  + heightBonus)
                  * (1f - heat * 0.5f)
                  * scoreBias;
        }

        private float EvaluateProtection(Vector3 coverPos, Vector3 threatPos)
        {
            // Cast from threat toward cover -- does something block it?
            Vector3 dir = coverPos - threatPos;
            float dist = dir.magnitude;
            if (Physics.Raycast(threatPos + Vector3.up, dir.normalized, dist - 0.5f))
                return 1f; // blocked -- good cover
            return 0.1f;   // exposed
        }

        private float EvaluateVisibility(Vector3 coverPos, Vector3 targetPos)
        {
            // Can we see target from peek position?
            Vector3 peekPos = coverPos + PeekDir * 0.5f + Vector3.up * 1.4f;
            Vector3 toTarget = targetPos - peekPos;
            if (!Physics.Raycast(peekPos, toTarget.normalized, toTarget.magnitude))
                return 1f;
            return 0f;
        }

        // ---------- Occupation -----------------------------------------------

        public void Occupy(StealthHuntAI unit)
        {
            Occupant = unit;
            _lastUsedTime = Time.time;
            _useCount++;
            HuntDirector.RegisterHeat(transform.position, 0.8f);
        }

        public void Release(StealthHuntAI unit)
        {
            if (Occupant == unit)
            {
                Occupant = null;
                HuntDirector.ClearHeat(transform.position);
            }
        }

        // ---------- Registry -------------------------------------------------

        private void OnEnable()
        {
            HuntDirector.RegisterCoverPoint(this);
        }

        private void OnDisable()
        {
            HuntDirector.UnregisterCoverPoint(this);
            if (Occupant != null) Release(Occupant);
        }

        // ---------- Gizmos ---------------------------------------------------

#if UNITY_EDITOR
        private void OnDrawGizmos()
        {
            Color col = type switch
            {
                CoverType.High => new Color(0.2f, 0.6f, 1f, 0.5f),
                CoverType.Corner => new Color(1f, 0.6f, 0.1f, 0.5f),
                _ => new Color(0.3f, 0.9f, 0.3f, 0.5f)
            };

            Gizmos.color = col;
            Gizmos.DrawWireCube(transform.position + Vector3.up * 0.5f,
                                 new Vector3(0.4f, 1f, 0.4f));

            // Peek direction arrow
            Gizmos.color = new Color(1f, 1f, 0f, 0.8f);
            Gizmos.DrawRay(transform.position + Vector3.up * 1.0f,
                           PeekDir * 1.2f);

            if (Application.isPlaying && IsOccupied)
            {
                Gizmos.color = Color.red;
                Gizmos.DrawWireSphere(transform.position + Vector3.up * 1.5f, 0.2f);
            }
        }
#endif
    }
}