using UnityEngine;
using UnityEngine.AI;
using System.Collections.Generic;

namespace StealthHuntAI
{
    /// <summary>
    /// Marks an area as an interesting search region for the HuntDirector.
    /// Now includes room memory -- units remember which regions they have searched
    /// and where the player has been found before.
    /// </summary>
    [AddComponentMenu("StealthHuntAI/Patrol Region")]
    public class PatrolRegion : MonoBehaviour
    {
        // ---------- Inspector -------------------------------------------------

        [Tooltip("Search radius of this region in world units.")]
        [Range(2f, 30f)] public float radius = 8f;

        [Tooltip("Extra interest weight. Higher = Director sends units here more often.")]
        [Range(0.1f, 3f)] public float interestBias = 1f;

        [Tooltip("If true this region is always considered regardless of player position.")]
        public bool alwaysActive = false;

        // ---------- Runtime scoring -------------------------------------------

        public float CurrentScore { get; set; }
        public float LastVisitTime { get; set; } = -999f;
        public float TimeSinceVisit => Time.time - LastVisitTime;

        // ---------- Room memory -----------------------------------------------

        /// <summary>Time.time when a unit last searched this region.</summary>
        public float LastSearchedTime { get; private set; } = -999f;

        /// <summary>Total number of times this region has been searched.</summary>
        public int SearchCount { get; private set; }

        /// <summary>Number of times the player has been found in this region.</summary>
        public int PlayerFoundCount { get; private set; }

        /// <summary>Time.time when player was last found here.</summary>
        public float LastPlayerFoundTime { get; private set; } = -999f;

        /// <summary>Seconds since this region was last searched.</summary>
        public float TimeSinceSearched => Time.time - LastSearchedTime;

        /// <summary>True if this region was auto-generated by HuntDirector.
        /// Auto-generated regions do not use persistent memory.</summary>
        public bool IsAutoGenerated { get; set; }

        // ---------- Static registry ------------------------------------------

        private static readonly List<PatrolRegion> _all = new List<PatrolRegion>();
        public static IReadOnlyList<PatrolRegion> All => _all;

        private void OnEnable()
        {
            if (!_all.Contains(this))
                _all.Add(this);

            // Reset memory on enable -- prevents stale data from previous sessions
            if (!IsAutoGenerated)
                ResetMemory();
        }

        private void OnDisable()
        {
            _all.Remove(this);
        }

        // ---------- Memory API ------------------------------------------------

        /// <summary>Called when a unit finishes searching this region.</summary>
        public void RecordSearch()
        {
            if (IsAutoGenerated) return;
            LastSearchedTime = Time.time;
            SearchCount++;
        }

        /// <summary>Called when a unit finds the player within this region.</summary>
        public void RecordPlayerFound()
        {
            if (IsAutoGenerated) return;
            PlayerFoundCount++;
            LastPlayerFoundTime = Time.time;
        }

        /// <summary>Reset all memory -- called on scene reload.</summary>
        public void ResetMemory()
        {
            LastSearchedTime = -999f;
            SearchCount = 0;
            PlayerFoundCount = 0;
            LastPlayerFoundTime = -999f;
        }

        // ---------- Scoring --------------------------------------------------

        public float Evaluate(Vector3 playerLastKnown, Vector3 flightVector,
                               float maxRange, Vector3 predictedFlightDir = default)
        {
            Vector3 toRegion = transform.position - playerLastKnown;
            float dist = toRegion.magnitude;

            if (dist > maxRange && !alwaysActive) return 0f;

            float distScore = 1f - Mathf.Clamp01(dist / maxRange);

            // Flight alignment -- actual observed flight vector
            float flightScore = 0.5f;
            if (flightVector.magnitude > 0.1f)
            {
                float dot = Vector3.Dot(flightVector.normalized, toRegion.normalized);
                flightScore = Mathf.Clamp01(dot * 0.5f + 0.5f);
            }

            // Predicted flight alignment -- historical pattern
            float predictedScore = 0.5f;
            if (predictedFlightDir.magnitude > 0.1f)
            {
                float dot = Vector3.Dot(predictedFlightDir.normalized, toRegion.normalized);
                predictedScore = Mathf.Clamp01(dot * 0.5f + 0.5f);
            }

            float recencyScore = Mathf.Clamp01(TimeSinceVisit / 30f);

            // Room memory scores
            float searchedPenalty = SearchCount > 0
                ? Mathf.Clamp01(1f - TimeSinceSearched / 60f) * 0.4f
                : 0f;

            float playerFoundBonus = PlayerFoundCount > 0
                ? Mathf.Clamp01(1f - (Time.time - LastPlayerFoundTime) / 120f) * 0.5f
                : 0f;

            return (distScore * 0.25f
                  + flightScore * 0.25f
                  + predictedScore * 0.15f
                  + recencyScore * 0.15f
                  + playerFoundBonus
                  - searchedPenalty)
                  * interestBias;
        }

        // ---------- Gizmos ---------------------------------------------------

        private void OnDrawGizmos()
        {
            Color baseColor = PlayerFoundCount > 0
                ? new Color(1f, 0.3f, 0.1f, 0.08f)
                : new Color(0.8f, 0.5f, 0.1f, 0.08f);

            Gizmos.color = baseColor;
            Gizmos.DrawSphere(transform.position, radius);
            baseColor.a = 0.35f;
            Gizmos.color = baseColor;
            Gizmos.DrawWireSphere(transform.position, radius);

#if UNITY_EDITOR
            if (Application.isPlaying)
            {
                string label = gameObject.name;
                if (PlayerFoundCount > 0)
                    label += " [found x" + PlayerFoundCount + "]";
                if (SearchCount > 0)
                    label += " [searched x" + SearchCount + "]";
                if (CurrentScore > 0.01f)
                    label += " " + CurrentScore.ToString("F2");

                UnityEditor.Handles.color = new Color(0.8f, 0.5f, 0.1f, 0.8f);
                UnityEditor.Handles.Label(
                    transform.position + Vector3.up * (radius * 0.3f + 0.5f),
                    label);
            }
            else
            {
                UnityEditor.Handles.color = new Color(0.6f, 0.4f, 0.1f, 0.5f);
                UnityEditor.Handles.Label(
                    transform.position + Vector3.up * (radius * 0.3f + 0.5f),
                    gameObject.name);
            }
#endif
        }
    }
}